### ISSUE TITLE
array_merge_recursive() error when editing json fields

### ISSUE THREAD

**Issue by blessen131** [ziming/json-field-for-backpack#11]
array_merge_recursive(): Expected parameter 2 to be an array, string given (View: /var/www/my-app/vendor/ziming/json-field-for-backpack/src/resources/views/fields/json.blade.php)

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.6.1
backpack/devtools: 1.3.5
backpack/generators: v3.3.17
backpack/permissionmanager: 6.0.17
backpack/pro: 1.6.6

ziming/json-field-for-backpack:1.2.0

**Comment by ziming** [comment]
Hi, did you cast your field as an array in your eloquent model?
