### ISSUE TITLE
Support for Backpack v6?

### ISSUE THREAD

**Issue by ziming** [ziming/json-field-for-backpack#7]
Just creating an issue to leave a reminder for myself later.

Would it just be a simple composer.json update to allow 1 more major version or more is needed to be done?

@tabacitu

**Comment by malek77z** [comment]
Thanks for the package.
I'm on Backpack 6, working my way though all the changes, and confirmed it mostly works, I forked and fixed some issues with the new tabler theme as well here:
https://github.com/malek77z/json-field-for-backpack
(css hack and version number updates)
Hope that helps!

**Comment by ziming** [comment]
Nice! could you make a PR when you ur done?

Screenshots will be nice too

Thank you @malek77z

**Comment by malek77z** [comment]
Just made a PR, first time ive done this github so hope all ok :)
Added a screen grab as well in the readme
